### ISSUE TITLE
phpspec/prophecy will be unbundled from phpunit/phpunit

### ISSUE THREAD

**Issue by localheinz** [Jan0707/phpstan-prophecy#161]
For reference, see https://github.com/sebastianbergmann/phpunit/issues/4141.

**Comment by InvisibleSmiley** [comment]
FTR: PHPUnit 9.1 deprecated the bundled methods. In order to get rid of the deprecation warnings, the phpspec/prophecy-phpunit dependency needs to be added and the new trait be used.

I really hope this extension can be updated to support the new setup. Looking forward to it!

**Comment by stof** [comment]
@jseparovic1 this should be closed as the trait from prophecy-phpunit is properly supported

**Comment by alexander-schranz** [comment]
Closing this as using prophecy-phpunit trait since a longer time without any issues.
