### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by localheinz** [Jan0707/phpstan-prophecy#285]
I do not use `phpstan/phpstan` and I do not use `phpspec/prophecy`.

Perhaps someone else has interest in maintaining this repository?

/cc @Jan0707

**Comment by ciaranmcnulty** [comment]
Maybe a lot of the stubs could be added to prophecy itself?

**Comment by alexander-schranz** [comment]
As the maintainance looks not a lot todo I could take it over. I mostly use the plugin on most projects and so if there are any issues to fix I would stumble over directly. And as using it also in other Open Source Software which I require to be keep compatible with newer PHP versions I also can tackle that part for this project. What I'm not planning to add new features to implement but for maintainance I could take it.

**Comment by localheinz** [comment]
Sounds good, @alexander-schranz!

Now we only need @Jan0707 to invite you here!

**Comment by Jan0707** [comment]
Done!

**Comment by jseparovic1** [comment]
@alexander-schranz Are you still interested in the maintaining the project? Let me know if any help is needed as we are actively using the plugin as well.

**Comment by alexander-schranz** [comment]
@jseparovic1  I will have at the open PR soonish. If you want please have a look at https://github.com/Jan0707/phpstan-prophecy/pull/327. I'm not 100% sure there what is broken and how we may can avoid it in a none breaking way.
