### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mondrake** [Jan0707/phpstan-prophecy#330]
Hi, any plan for a new point release? #316 deserves one IMHO, otherwise we are forced to require dev-master to avoid PHPStan failing.

Coming here from Drupal issue https://www.drupal.org/project/drupal/issues/3425412#comment-15520444

Thanks

**Comment by alexander-schranz** [comment]
Current master is tagged to avoid this blocking part for you and others. https://github.com/Jan0707/phpstan-prophecy/releases/tag/1.0.1

Other releases still planned with open fixes.

**Comment by mondrake** [comment]
Thanks
