### ISSUE TITLE
jangregor/phpstan-prophecy failed to update, invalid composer.json data

### ISSUE THREAD

**Issue by Jan0707** [Jan0707/phpstan-prophecy#331]
Just got a mail from packagist.org

> The jangregor/phpstan-prophecy package of which you are a maintainer has
> failed to update due to invalid data contained in your composer.json.
> Please address this as soon as possible since the package stopped updating.
> 
> It is recommended that you use `composer validate` to check for errors when you
> change your composer.json.
> 
> Below is the update log which should highlight errors as
> "Skipped branch ...":
> 
> [Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches
> 
> Skipped branch master, Invalid package information:
> conflict.phpspec/prophecy : this version constraint cannot possibly match anything (=2.0.0)
> conflict.phpunit/phpunit : this version constraint cannot possibly match anything (=10.0.0)

**Comment by alexander-schranz** [comment]
Thx @Jan0707 this will be fixed in https://github.com/Jan0707/phpstan-prophecy/pull/332
