### ISSUE TITLE
PHPStan 2 compatability

### ISSUE THREAD

**Issue by jblotus** [Jan0707/phpstan-prophecy#346]
Hello! PHPStan v2 has been released.

https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md#upgrading-guide-for-extension-developers

Would it be possible to get a new major version of this released to support that constraint?

Currently I am working around the issue using composer `replace` keyword.

**Comment by alexander-schranz** [comment]
There a a few deprecations with instanceof which we need to tackle. If you want to help check https://github.com/Jan0707/phpstan-prophecy/pull/345

**Comment by sasezaki** [comment]
Hi all.
There is still in progress at #348.

I believe we have completed most of the work required for the PHPStan2 update.

You can quickly test with fork. with fork repository
https://getcomposer.org/doc/05-repositories.md#repositories
- `composer remove --dev jangregor/phpstan-prophecy`
- update phpstan2
- add repositories
```json
"repositories": [
        {
            "name": "jangregor/phpstan-prophecy",
            "type": "vcs",
            "url": "https://github.com/sasezaki/phpstan-prophecy"
        }
    ],
```
- `composer require --dev jangregor/phpstan-prophecy:dev-phpstan2 `

I still need some help. Any help would be appreciated.
 - Update README example code.
 - Update gha matrix to test with PHP 8, PHPUnit 10,11

**Comment by Jean85** [comment]
> I still need some help. Any help would be appreciated.
> 
>     * Update README example code.
> 
>     * Update gha matrix to test with PHP 8, PHPUnit 10,11

GHA done in #351, what do you think we should update in the readme? It looks fine to me.
Also, is there any other blocker?

**Comment by alexander-schranz** [comment]
I updated the docker setup for dev development.

Anything you think is missing @stof, @Jean85, @sasezaki ?

**Comment by sasezaki** [comment]
@alexander-schranz 
I've just added a new PR #353 to update README. It is not a blocker for the PHPStan 2 support release.
I don't think there's anything left to do except this PR.

**Comment by sasezaki** [comment]
Thank you, everyone, as well!
