### ISSUE TITLE
phpstan-prophecy doesn't support phpstan v.0.11

### ISSUE THREAD

**Issue by c24-gesundheit-blackfire** [Jan0707/phpstan-prophecy#35]
Hi Jan. Tried to update my phpstan/phpstan to version 0.11 but phpstan-prophecy 0.2.0 prevents phpstan/phpstan from updating to 0.11 because there is an hard requirement to ^0.10.

**Comment by Jean85** [comment]
Already handled by #33.

**Comment by c24-gesundheit-blackfire** [comment]
Hey Jean, thanks for the fast response. Haven't noticed it yet. My fault.

**Comment by c24-gesundheit-blackfire** [comment]
Solved with https://github.com/Jan0707/phpstan-prophecy/pull/33.
