### ISSUE TITLE
Support for attributes of mocked class

### ISSUE THREAD

**Issue by alexander-schranz** [Jan0707/phpstan-prophecy#49]
E.g.:

```php
use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Component\HttpFoundation\Request;

$this->attributes = $this->prophesize(ParameterBag::class);

$this->request = $this->prophesize(Request::class);
$this->request->attributes = $this->attributes->reveal();
```

Will error with:

```bash
Access to an undefined property
Prophecy\Prophecy\ObjectProphecy<Symfony\Component\HttpFoundation\Request>::$attributes.
```

**Comment by Jean85** [comment]
In that case, it's right that way. Mocking those is discouraged by Prophecy, see: https://github.com/phpspec/prophecy/issues/86

**Comment by alexander-schranz** [comment]
Can understand that in many cases but I need to mock it to test that specific functions are called and specific functions should not be called and thats only possible with mocking.

**Comment by Jean85** [comment]
That's still testing internal behavior, I would not advise it. You can instead inspect the final `$request` state after calling the unit under test.

**Comment by Jan0707** [comment]
@Jean85 is right.
