### ISSUE TITLE
Problem with Test private variable @var typehints

### ISSUE THREAD

**Issue by angelsk** [Jan0707/phpstan-prophecy#50]
Stan error

`Property App\Tests\Validator\Constraints\HasBasketValidatorTest::$basketRepository (App\Repository\BasketRepository) does not accept Prophecy\Prophecy\ObjectProphecy<App\Repository\BasketRepository>.`

Code

```
class HasBasketValidatorTest extends ConstraintValidatorTestCase
{
    /**
     * @var BasketRepository
     */
    private $basketRepository;

    protected function createValidator()
    {
        $this->basketRepository = $this->prophesize(BasketRepository::class);
    }
.....
}
```

**Comment by Jean85** [comment]
That is correct. You're assigning the prophecy and not the proper mock to the property. You should remove the PHPDoc from the property.

**Comment by angelsk** [comment]
@Jean85 But it works perfectly if I use the MockBuilder - no problem with typehints at all.

**Comment by Jean85** [comment]
Yes, because the PHPUnit mock builder works in a fundamentally different way (which I personally don't like). Prophecy return the stub calling `reveal()` instead.
