### ISSUE TITLE
phpstan-prophecy with PHPStan 0.12.0

### ISSUE THREAD

**Issue by AlexandruGG** [Jan0707/phpstan-prophecy#69]
Hello,

PHPStan 0.12.0 came out recently and it looks like `phpstan-prophecy` is not compatible with it at the moment. Even if I try to get around the version restriction, when running PHPStan I get the following error:

_Fatal error: Class JanGregor\Prophecy\Reflection\ObjectProphecyMethodReflection contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\MethodReflection::isDeprecated, PHPStan\Reflection\MethodReflection::getDeprecatedDescription, PHPStan\Reflection\MethodReflection::isFinal, ...) in /var/www/html/vendor/jangregor/phpstan-prophecy/src/Reflection/ObjectProphecyMethodReflection.php on line 12_

I saw https://github.com/Jan0707/phpstan-prophecy/pull/67, however is there any timeline as to when this can be addressed?

Thanks!

**Comment by PedroTroller** [comment]
@AlexandruGG :eyes: https://github.com/Jan0707/phpstan-prophecy/pull/67
